rules: []
rulesConfigs: []
hooks: []
pages: []
resourceServers:
  - name: backend
    identifier: backend
    allow_offline_access: false
    scopes: []
    signing_alg: RS256
    skip_consent_for_verifiable_first_party_clients: true
    token_lifetime: 86400
    token_lifetime_for_web: 7200
clients:
  - name: API Explorer Application
    allowed_clients: []
    app_type: non_interactive
    callbacks: []
    client_aliases: []
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_basic
  - name: backend
    allowed_clients: []
    app_type: non_interactive
    callbacks: []
    client_aliases: []
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - client_credentials
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: non-expiring
      leeway: 0
      infinite_token_lifetime: true
      infinite_idle_token_lifetime: true
      token_lifetime: 31557600
      idle_token_lifetime: 2592000
      rotation_type: non-rotating
    sso_disabled: false
    token_endpoint_auth_method: client_secret_post
  - name: frontend
    allowed_clients: []
    allowed_logout_urls:
      - http://localhost:4200/#/login
    allowed_origins:
      - http://localhost:4200
    app_type: spa
    callbacks:
      - http://localhost:4200/#/dashboard
    client_aliases: []
    cross_origin_auth: false
    custom_login_page_on: true
    grant_types:
      - authorization_code
      - implicit
      - refresh_token
    is_first_party: true
    is_token_endpoint_ip_header_trusted: false
    jwt_configuration:
      alg: RS256
      lifetime_in_seconds: 36000
      secret_encoded: false
    native_social_login:
      apple:
        enabled: false
      facebook:
        enabled: false
    oidc_conformant: true
    refresh_token:
      expiration_type: expiring
      leeway: 0
      token_lifetime: 2592000
      idle_token_lifetime: 1296000
      infinite_token_lifetime: false
      infinite_idle_token_lifetime: false
      rotation_type: rotating
    sso_disabled: false
    token_endpoint_auth_method: none
    web_origins:
      - http://localhost:4200
databases:
  - name: Username-Password-Authentication
    strategy: auth0
    enabled_clients:
      - API Explorer Application
      - backend
      - frontend
    is_domain_connection: false
    options:
      mfa:
        active: true
        return_enroll_settings: true
      passwordPolicy: good
      strategy_version: 2
      brute_force_protection: true
    realms:
      - Username-Password-Authentication
connections:
  - name: google-oauth2
    strategy: google-oauth2
    enabled_clients:
      - frontend
    is_domain_connection: false
    options:
      email: true
      gmail: false
      orkut: false
      scope:
        - email
        - profile
      sites: false
      tasks: false
      blogger: false
      profile: true
      youtube: false
      calendar: false
      contacts: false
      analytics: false
      client_id: ''
      moderator: false
      coordinate: false
      picasa_web: false
      google_plus: false
      google_books: false
      google_drive: false
      spreadsheets: false
      document_list: false
      latitude_best: false
      latitude_city: false
      url_shortener: false
      webmaster_tools: false
      chrome_web_store: false
      allowed_audiences: ''
      adsense_management: false
      google_drive_files: false
      coordinate_readonly: false
      google_cloud_storage: false
      content_api_for_shopping: false
      google_affiliate_network: false
tenant:
  enabled_locales:
    - en
  flags:
    revoke_refresh_token_grant: false
    disable_clickjack_protection_headers: false
  sandbox_version: '16'
emailProvider: {}
emailTemplates: []
clientGrants:
  - client_id: backend
    audience: https://##AUTH0_DOMAIN##/api/v2/
    scope:
      - read:client_grants
      - create:client_grants
      - delete:client_grants
      - update:client_grants
      - read:users
      - update:users
      - delete:users
      - create:users
      - read:users_app_metadata
      - update:users_app_metadata
      - delete:users_app_metadata
      - create:users_app_metadata
      - read:user_custom_blocks
      - create:user_custom_blocks
      - delete:user_custom_blocks
      - create:user_tickets
      - read:clients
      - update:clients
      - delete:clients
      - create:clients
      - read:client_keys
      - update:client_keys
      - delete:client_keys
      - create:client_keys
      - read:connections
      - update:connections
      - delete:connections
      - create:connections
      - read:resource_servers
      - update:resource_servers
      - delete:resource_servers
      - create:resource_servers
      - read:device_credentials
      - update:device_credentials
      - delete:device_credentials
      - create:device_credentials
      - read:rules
      - update:rules
      - delete:rules
      - create:rules
      - read:rules_configs
      - update:rules_configs
      - delete:rules_configs
      - read:hooks
      - update:hooks
      - delete:hooks
      - create:hooks
      - read:actions
      - update:actions
      - delete:actions
      - create:actions
      - read:email_provider
      - update:email_provider
      - delete:email_provider
      - create:email_provider
      - blacklist:tokens
      - read:stats
      - read:insights
      - read:tenant_settings
      - update:tenant_settings
      - read:logs
      - read:logs_users
      - read:shields
      - create:shields
      - update:shields
      - delete:shields
      - read:anomaly_blocks
      - delete:anomaly_blocks
      - update:triggers
      - read:triggers
      - read:grants
      - delete:grants
      - read:guardian_factors
      - update:guardian_factors
      - read:guardian_enrollments
      - delete:guardian_enrollments
      - create:guardian_enrollment_tickets
      - read:user_idp_tokens
      - create:passwords_checking_job
      - delete:passwords_checking_job
      - read:custom_domains
      - delete:custom_domains
      - create:custom_domains
      - update:custom_domains
      - read:email_templates
      - create:email_templates
      - update:email_templates
      - read:mfa_policies
      - update:mfa_policies
      - read:roles
      - create:roles
      - delete:roles
      - update:roles
      - read:prompts
      - update:prompts
      - read:branding
      - update:branding
      - delete:branding
      - read:log_streams
      - create:log_streams
      - delete:log_streams
      - update:log_streams
      - create:signing_keys
      - read:signing_keys
      - update:signing_keys
      - read:limits
      - update:limits
      - create:role_members
      - read:role_members
      - delete:role_members
      - read:entitlements
      - read:attack_protection
      - update:attack_protection
      - read:organizations
      - update:organizations
      - create:organizations
      - delete:organizations
      - create:organization_members
      - read:organization_members
      - delete:organization_members
      - create:organization_connections
      - read:organization_connections
      - update:organization_connections
      - delete:organization_connections
      - create:organization_member_roles
      - read:organization_member_roles
      - delete:organization_member_roles
      - create:organization_invitations
      - read:organization_invitations
      - delete:organization_invitations
      - read:organizations_summary
      - create:actions_log_sessions
      - create:authentication_methods
      - read:authentication_methods
      - update:authentication_methods
      - delete:authentication_methods
      - read:client_credentials
      - create:client_credentials
      - update:client_credentials
      - delete:client_credentials
  - client_id: backend
    audience: backend
    scope: []
guardianFactors:
  - name: duo
    enabled: false
  - name: email
    enabled: false
  - name: otp
    enabled: false
  - name: push-notification
    enabled: false
  - name: recovery-code
    enabled: false
  - name: sms
    enabled: false
  - name: webauthn-platform
    enabled: false
  - name: webauthn-roaming
    enabled: false
guardianFactorProviders: []
guardianFactorTemplates: []
guardianPolicies:
  policies: []
guardianPhoneFactorSelectedProvider:
  provider: auth0
guardianPhoneFactorMessageTypes:
  message_types: []
roles: []
branding:
  templates: []
prompts:
  customText: {}
  universal_login_experience: new
migrations: {}
actions:
  - name: initial-setup-login
    code: ./actions/initial-setup-login/code.js
    dependencies:
      - name: axios
        version: 1.4.0
    deployed: true
    runtime: node16
    secrets:
      - name: API_KEY
        value: ##AUTH0_ACTION_API_KEY##
      - name: BACKEND_DOMAIN
        value: ##AUTH0_ACTION_BACKEND_DOMAIN_URL##
    status: built
    supported_triggers:
      - id: post-login
        version: v3
triggers:
  post-login:
    - action_name: initial-setup-login
      display_name: initial-setup-login
organizations: []
attackProtection:
  breachedPasswordDetection:
    enabled: false
    shields: []
    admin_notification_frequency: []
    method: standard
    stage:
      pre-user-registration:
        shields: []
  bruteForceProtection:
    enabled: true
    shields:
      - block
      - user_notification
    mode: count_per_identifier_and_ip
    allowlist: []
    max_attempts: 10
  suspiciousIpThrottling:
    enabled: true
    shields:
      - admin_notification
      - block
    allowlist: []
    stage:
      pre-login:
        max_attempts: 100
        rate: 864000
      pre-user-registration:
        max_attempts: 50
        rate: 1200
logStreams: []
themes: []
